# Dobot Magician Protocol IDs (Official Documentation)

# System Commands
GET_POSE = 10
CLEAR_ALARM = 20
SET_HOME_PARAMS = 30
GET_HOME_PARAMS = 31

# Arm Enable / Disable
SET_ARM_ENABLED = 246        # Enable arm motors
GET_ARM_ENABLED = 247

# PTP Motion Commands
SET_GET_PTP_COMMON_PARAMS = 80
SET_PTP_COORDINATE_PARAMS = 81
SET_PTP_JUMP_PARAMS = 82
SET_PTP_CMD = 84             # Perform PTP movement

# CP (Continuous Path) Commands
SET_CP_CMD = 91

# End Effector Commands
SET_END_EFFECTOR_PARAMS = 60
SET_END_EFFECTOR_LASER = 61
SET_END_EFFECTOR_SUCTION_CUP = 62
SET_END_EFFECTOR_GRIPPER = 63

# Queued Commands
SET_QUEUED_CMD_START_EXEC = 240
SET_QUEUED_CMD_STOP_EXEC = 241
SET_QUEUED_CMD_FORCE_STOP_EXEC = 242
SET_QUEUED_CMD_START_DOWNLOAD = 243
SET_QUEUED_CMD_CLEAR = 245

# I/O Commands
GET_IODO = 130
SET_IODO = 131

# Misc
SET_JOG_CMD = 93
GET_DEVICE_VERSION = 0
